[config]
# If set to enabled, it will check for updates when you run the matugen command, notifying you that an update is avaiable.
# WARNING: Matugen needs to be compiled with the `update-informer` feature for this to work.
version_check = false

# The color which should be used as the source_color if no good color was found from an image.
# Can be defined in any css format.
# The cli flag will override this if used.
fallback_color = "#ffbf9b"

# Enables caching which will cache the colorscheme, custom colors, etc. into a cache folder located in
# Windows: C:\Users\user\AppData\Roaming\InioX\matugen\cache\images\<file>
# Linux: $XDG_CACHE_HOME/matugen/<file> or $HOME/.cache/matugen/images/<file>
# MacOS: $HOME/Library/Caches/matugen/images/<file>
# The file follows this naming: <image_name>.<image_extension>.<image_hash>.json
# For example: testimage.png.0cfd2d624b3d09bf6246b7be9ca79e207e7aa1189d961d44949628b99811bb9d.json
# You can modify the cache and it will then be loaded when using the same image.
# The colors are defined using the #RRGGBBAA format.
caching = false

# Changing the syntax
# Expr is for keywords like {{ <keyword> }}
expr_prefix = "{{"
expr_postfix = "}}"

# Block is for stuff like for loops etc.
block_prefix = "<*"
block_postfix = "*>"

# Imports json files just like `--import-json` does.
# Relative paths will be resolved from the path `config.toml` is in.


# [templates.name1]
# # Relative paths will be resolved from the path `config.toml` is in.
# input_path = "./templates/colors.scss"
# output_path = "./out/colors.scss"

# # For testing of the `--continue-on-error` flag
# # [templates.ishoulderror]
# # Relative paths will be resolved from the path `config.toml` is in.
# # input_path = "./error-testing.txt"
# # output_path = "./a/error-testing.txt"

# # This will use a different input path depending on what mode you use.
# # input_path_modes = { dark = "./colors.whatever-extension", light = "./colors.whatever-extension" }

# # This will compare all of the colors inside the array with the color you set as `compare_to`, and returns the closest color to it.
# # You can then use `{{closest_color}}` inside hooks.
# colors_to_compare = [
#     { name = "black", color = "#000000" },
#     { name = "red", color = "#ff0000" },
#     { name = "maroon", color = "#800000" },
#     { name = "yellow", color = "#ffff00" },
#     { name = "olive", color = "#808000" },
#     { name = "lime", color = "#00ff00" },
#     { name = "green", color = "#008000" },
#     { name = "aqua", color = "#00ffff" },
#     { name = "teal", color = "#008080" },
#     { name = "blue", color = "#0000ff" },
#     { name = "navy", color = "#000080" },
#     { name = "fuchsia", color = "#ff00ff" },
#     { name = "purple", color = "#800080" },
# ]
# compare_to = "{{colors.primary.hex}}"

# # Runs before the template is exported. You can use keywords here.
# # If you want the command to be async, add an & symbol to the end of the command on unix.
# # pre_hook = 'echo "source color {{colors.source_color.default.hex}}, source image {{image}}, closest color {{closest_color}}"'
# # # Runs after the template is exported. You can use keywords here.
# # # If you want the command to be async, add an & symbol to the end of the command on unix.
# # post_hook = 'echo "after gen"'

# # For overriding the prefix for a specific template only
# expr_prefix = "{{"
# expr_postfix = "}}"

# Only hex values
# https://m3.material.io/styles/color/advanced/adjust-existing-colors#1cc12e43-237b-45b9-8fe0-9a3549c1f61e
# If you want to use the original color without any harmonization, add `_source` after the name like: `{{ color_source }}`
# Example: To use the original red color you would use `{{ red_source }}` instead of `{{ red }}`


[templates.yazi]
input_path = './templates/yazi-colors.toml'
output_path = '~/.config/yazi/theme.toml'


[templates.ghostty]
input_path = './templates/ghostty-config'
output_path = '~/.config/ghostty/themes/Matugen'


[templates.starship]
input_path = './templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.spotify]
input_path = './templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = "awk '{sub(/#/,\" \")}1' ~/.config/spicetify/Themes/Sleek/color.ini > ~/.config/spicetify/Themes/Sleek/temp.txt && mv ~/.config/spicetify/Themes/Sleek/temp.txt ~/.config/spicetify/Themes/Sleek/color.ini"

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './templates/qt5ct.colors'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qt5ct.colors'
output_path = '~/.config/qt6ct/colors/matugen.conf'
